url: https://octokatt.github.io
baseurl: /octokatt.github.io/

# Site settings
title: Katt Kennedy
email: katt@fatehold.com
description: "Katt Kennedy's personal portfolio.  They specialize in data science, UX research, data visualization, storytelling, design, and being awesome.  Generalists beat specialists for utility."


# Team section, now repurposed for media grouping
people:
- name: Emerging Leaders Mentorship
  pic: 1
  position: Mentoring the Next Generation of Leaders
  social:
    - title: linkedin
      url: https://www.linkedin.com/company/emergingleaderspdx/
    - title: instagram
      url: https://www.instagram.com/emergingleaderspdx/
    - title: twitter
      url: https://twitter.com/EmergingLdrsPDX

- name: Out in Tech
  pic: 2
  position: Community of LGBTQ+ Tech Leaders
  social:
    - title: instagram
      url: https://www.instagram.com/outintech/
    - title: twitter
      url: https://twitter.com/OutInTech
    - title: linkedin
      url: https://www.linkedin.com/company/outintech/

- name: Games to Gather
  pic: 3
  position: Resources for Game Designers
  social:
    - title: facebook
      url: https://www.facebook.com/gamestogatherpdx/
    - title: twitter
      url: https://twitter.com/gamestogather
    - title: envelope-o
      url: mailto:board@gamestogather.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/octokatt
  - title: linkedin
    url: http://linkedin.com/in/kattkennedy
  - title: twitter
    url: http://twitter.com/octokatt_bot



# Postal address (add as many lines as necessary)
address:
  - line: Greater Portland Metro
  - line: Vancouver, WA 98682

# Build settings
markdown: kramdown
permalink: pretty