url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Katt Kennedy
email: katt@fatehold.com
description: "Katt Kennedy's personal portfolio.  They specialize in data science, UX research, data visualization, storytelling, design, and being awesome.  Generalists beat specialists for utility."


# Team section, now repurposed for media grouping
people:
- name: Emerging Leaders Mentorship
  pic: 1
  position: Mentoring the Next Generation of Leaders
  social:
    - title: medium
      url: #
    - title: slideshare
      url: #
    - title: leanpub
      url: #

- name: Me!
  pic: 2
  position: Essays, Talks, and Code Quick-starts
  social:
    - title: medium
      url: #
    - title: github
      url: #
    - title: slideshare
      url: #

- name: Games to Gather
  pic: 3
  position: Resources for Game Designers
  social:
    - title: dribbble
      url: #
    - title: instagram
      url: #
    - title: etsy
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/octokatt
  - title: linkedin
    url: http://linkedin.com/in/kattkennedy
  - title: twitter
    url: http://twitter.com/octokatt_bot
  - title: instagram
    url: 
  - title: dribbble
    url: 


# Postal address (add as many lines as necessary)
address:
  - line: Greater Portland Metro
  - line: Vancouver, WA 98682

# Build settings
markdown: kramdown
permalink: pretty