url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Katt Kennedy
email: katt@fatehold.com
description: "Katt Kennedy's personal portfolio.  They specialize in data science, UX research, data visualization, storytelling, design, and being awesome.  Generalists beat specialists for utility."


# Team names, titles and social links
people:
- name: Writing
  pic: 1
  position: Essays and Presentations around the Web
  social:
    - title: medium
      url: #
    - title: slideshare
      url: #
    - title: leanpub
      url: #

- name: Code
  pic: 2
  position: Cookie-cutter Project Templates
  social:
    - title: medium
      url: #
    - title: github
      url: #
    - title: bitbucket
      url: #

- name: Designs
  pic: 3
  position: Visual Designs for Business and Nerdery
  social:
    - title: dribbble
      url: #
    - title: instagram
      url: #
    - title: etsy
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/octokatt
  - title: linkedin
    url: http://linkedin.com/in/kattkennedy
  - title: twitter
    url: http://twitter.com/octokatt_bot
  - title: instagram
    url: 
  - title: dribbble
    url: 


# Postal address (add as many lines as necessary)
address:
  - line: Greater Portland Metro
  - line: Vancouver, WA 98682

# Build settings
markdown: kramdown
permalink: pretty